[package]
name = "ip-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ip-core = { version = "0.1.0", path = "../ip-core" }
serde = { version = "1.0.229", features = ["derive"] }
subtle = "2.6.1"
thiserror.workspace = true
toml = "1.1.5"
tracing-core = "0.1.36"
url = { version = "2.5.8", features = ["serde"] }
zeroize = "1.9.0"
