[package]
name = "ip-config"
description = "The configuration file intelli-prism is started from"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ip-core = { version = "0.1.0", path = "../ip-core" }
serde.workspace = true
subtle = "2.6.1"
thiserror.workspace = true
toml = "1.1.5"
tracing-core = "0.1.36"
url = { version = "2.5.8", features = ["serde"] }
zeroize.workspace = true
