[package]
name = "intelli-prism"
version.workspace = true
edition.workspace = true

[dependencies]
axum = "0.8.9"
http-body-util = "0.1.5"
ip-auth = { version = "0.1.0", path = "crates/ip-auth" }
ip-cache = { version = "0.1.0", path = "crates/ip-cache", default-features = false }
ip-config = { version = "0.1.0", path = "crates/ip-config" }
ip-core = { version = "0.1.0", path = "crates/ip-core" }
ip-gateway = { version = "0.1.0", path = "crates/ip-gateway" }
ip-plugin = { version = "0.1.0", path = "crates/ip-plugin" }
ip-storage = { version = "0.1.0", path = "crates/ip-storage", default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
ip-core = { path = "crates/ip-core" }
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }

[dev-dependencies]
async-trait = "0.1.92"
bytes = "1.12.1"
http-body-util = "0.1.5"
ip-cache = { version = "0.1.0", path = "crates/ip-cache", features = ["standalone-cache"] }
ip-storage = { version = "0.1.0", path = "crates/ip-storage", features = ["standalone-storage"] }
serde_json = "1.0.151"
sqlx = { version = "0.9.0", default-features = false, features = ["runtime-tokio", "postgres"] }
tower = "0.5.3"
wat = "1.259.0"

[features]
default = ["fast-storage", "cluster-cache"]
standalone-storage = ["ip-storage/standalone-storage"]
fast-storage = ["ip-storage/fast-storage"]
standalone-cache = ["ip-cache/standalone-cache"]
cluster-cache = ["ip-cache/cluster-cache"]
