[package]
name = "ip-plugin"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = "0.1.92"
bytes = "1.12.1"
http = "1.5.0"
ip-auth = { version = "0.1.0", path = "../ip-auth" }
ip-core = { version = "0.1.0", path = "../ip-core" }
ip-gateway = { version = "0.1.0", path = "../ip-gateway" }
ip-storage = { version = "0.1.0", path = "../ip-storage", default-features = false }
thiserror.workspace = true
tokio.workspace = true
tracing = "0.1.44"
wasmtime = { version = "48.0.2", default-features = false, features = ["cranelift", "pooling-allocator", "runtime", "std"] }

[dev-dependencies]
ip-storage = { version = "0.1.0", path = "../ip-storage", features = ["standalone-storage"] }
wat = "1.259.0"
